version: '3.8'

services:
  app:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_KEY: ${JWT_KEY}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SENDER: ${MAIL_SENDER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_ADDR: redis:6379
    ports:
      - "80:8080"
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.2-alpine3.17

  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
